### ISSUE TITLE
[Proposal] the `annotations` should be a TaskKey and not a SettingKey

### ISSUE THREAD

**Issue by guizmaii** [lightbend/sbt-reactive-app#125]
Hi,

Due to the fact that the `annotations` is a `SettingKey` and `appName` is a `TaskKey`, I can't write this:

```
annotations := Map(
  s"ad.datadoghq.com/${appName.value}.check_names"  -> Json.arr(JsString("jmx")).toString(),
  s"ad.datadoghq.com/${appName.value}.init_configs" -> "[{}]",
  s"ad.datadoghq.com/${appName.value}.instances"    -> Json.arr(Json.obj("host" -> "%%host%%", "port" -> 7199)).toString()
)
```

(See Datadog doc: https://docs.datadoghq.com/agent/autodiscovery/#template-source-kubernetes-pod-annotations)

A solution could be to change `annotations` to a `TaskKey`.
Another solution could be to change `appName` to a `SettingKey`

What's your opinion about that ?

**Comment by dwijnand** [comment]
I had a little look at what would happen in trying to make `appName` a setting key, and it fails because its default definition depends on `lagomRawEndpoints`, which in turn depends on a bunch of task keys (`managedClasspath`, `fullClasspath`, `scalaInstance`...).

So to support this use case `annotations` would have to become a `TaskKey`.
