### ISSUE TITLE
Unknown deployment target: "". Available: minikube

### ISSUE THREAD

**Issue by shivapreals** [lightbend/sbt-reactive-app#157]
after running sbt deploy minikube 
unknown deployment target avaiable

**Comment by TimMoore** [comment]
Hi @shivapreals,

https://discuss.lightbend.com/ is a better place to ask for help. That lets us keep GitHub focused on confirmed bugs.

In this case, be sure that if you are running directly from the shell, that you've quoted the command correctly:

```
sbt "deploy minikube"
```

Otherwise, `sbt` will parse it as two separate commands, "deploy" and "minikube", rather than parsing "minikube" as an argument to the "deploy" command.
