### ISSUE TITLE
Docker images are built on host JDK but based on separate JDK

### ISSUE THREAD

**Issue by megri** [lightbend/sbt-reactive-app#158]
I noticed this while trying to build/`deploy minikube` [the online auction project](https://github.com/lagom/online-auction-scala/). I was running JDK 11 locally and everything seemed fine but the services could not start due to a mismatch between the generated .class-files and the runtime JDK.

```
Uncaught error from thread [application-akka.actor.default-dispatcher-10]: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
```
In order to maintain reproducible builds, the generated Dockerfile should itself build the required resources with the target JVM.

**Comment by TimMoore** [comment]
This project is built on top of the [`sbt-native-packager` Docker image support](https://www.scala-sbt.org/sbt-native-packager/formats/docker.html). It's fundamental to the design of `sbt-native-packager` that it relies on the normal sbt compilation process and then packages as a following step. This is designed to fit naturally with the typical sbt workflow, to allow various packaging targets to be generated in the same way, and to generate lean Docker images without the need to include build tools or source code in the container.

A couple of options you could think about are:

- Run the entire sbt process inside a Docker container using the same Java base image (I found an example at https://github.com/htch/scala-docker-build-example but I haven't tried it… you might need to use a custom build image)
- Use your own `Dockerfile` and the normal Docker build workflow instead of `sbt-reactive-app`/`sbt-native-packager`, and take advantage of [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) to use a separate build image.
- Use another approach based on builder images such as Red Hat's [`source-to-image` (s2i)](https://github.com/openshift/source-to-image)

We're planning to publish a guide to using s2i with sbt in the future.

Note also that Lagom does not support Java 11 at this time, so you should stick with Java 8 everywhere.
